# Generated by Django 4.0.6 on 2022-07-30 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_remove_comment_is_solved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
